"""task_id to id and added to is_complete

Revision ID: 41253d4cc23f
Revises: 
Create Date: 2023-01-31 07:33:21.328625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41253d4cc23f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
